#!/bin/bash

GREEN='\033[0;32m'
RED='\033[0;31m'
DEF='\033[0m'
	if [ $# -eq 1 ] ; then	
		echo "Pinging..."
		ping -c 1 $1 > /dev/null
		if [ $? -eq 0 ]; then
			echo -e IP $1 is ${GREEN}UP${DEF}."\n"
			whois $1 | grep Organization | tail -n 1
			nslookup $1 | grep name | cut -d '=' -f2- | cut -c 2-
			nslookup $1 | grep Server
		else
			echo -e IP $1 is ${RED}DOWN${DEF}."\n"
		fi
	else
		echo "usage: ./03 host"
	fi
#$? output last executed command
